source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts

exclude: [_internal, bootstrap.scss, Gemfile.lock, Gemfile, README.md]

# safe: true
lsi: false

redcarpet:
  extensions: []

encoding: utf-8
