source:      .
destination: ./_site
plugins:     ./_plugins
layouts:     ./_layouts

exclude: [templates, Gemfile.lock, Gemfile, scratch, README.md]

safe: true
lsi: false

redcarpet:
  extensions: []
